name: Deploy

on:
  push:
    branches: [ main ]

jobs:  
  build-and-deploy:
    name: "build and deploy"
    runs-on: ubuntu-latest
    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      HOST_PATH: ${{ secrets.HOST_PATH }}
      TEST_ENV: This is my own ENV FF
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - run: echo "finished $TEST_ENV"
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
            echo "$SSH_KEY" > ~/.ssh/staging.key
            cat ~/.ssh/staging.key
            chmod 600 ~/.ssh/staging.key
            cat >>~/.ssh/config <<END
            Host sb-droplet
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/staging.key
              StrictHostKeyChecking no
      - run: yarn install
      - run: yarn build:frontend
      - run: yarn build:backend
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: $SSH_HOST
          username: $SSH_USER
          key: $SSH_KEY
          script: |
            cd $HOST_PATH
            git fetch
            git reset --hard origin/main

