name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{secrets.SSH_KEY}}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install
      - run: yarn build:frontend
      - run: yarn build:backend
      - run: echo "$SSH_KEY"
      - run: echo "$SSH_HOST"      
      - run: echo "$SSH_USER"
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
            echo "$SSH_KEY" > ~/.ssh/staging.key
            chmod 600 ~/.ssh/staging.key
            cat >>~/.ssh/config <<END
            Host staging
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/staging.key
              StrictHostKeyChecking no
            END
        env:
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
          SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
      - name: Check out the source
        run: ssh staging 'cd ~/../var/www/pm.rem029.com/ && git fetch && git reset --hard origin/master'

